// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zoxbhfxdhtakwmmaycym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpveGJoZnhkaHRha3dtbWF5Y3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDQ4MTcsImV4cCI6MjA2OTMyMDgxN30.rnZLti7pt6uop4M9mhzqNVB_noCR8yTyeS54fdUVn7k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});